---
---

<link rel="stylesheet" href="styles.css" type="text/css">

#### PHP 2530: Bayesian Statistical Analysis 
##### Teaching Assistant
<br/>

##### Course Description  

Surveys the state of the art in Bayesian methods and their applications. Discussion of the fundamentals followed by more advanced topics including hierarchical models, Markov Chain Monte Carlo, and other methods for sampling from the posterior distribution, robustness, and sensitivity analysis, and approaches to model selection and diagnostics. Features nontrivial applications of Bayesian methods from diverse scientific fields, with emphasis on biomedical research. Prerequisites: APMA 1650, PHP 2510, PHP 2511, or equivalent. Open to advanced undergraduates with permission from the instructor.

##### Role

I provided one-on-one tutelage, email correspondence and group assistance during twice-weekly hour-long office hours. Time was spent building intuition around Bayesian statistics, walking through challenging problem sets and debugging code. I also graded five problem sets for twenty-one M.S. and Ph.D. students. Textbook was [_Bayesian Data Analysis_, Gelman et al.](http://www.stat.columbia.edu/~gelman/book/)