---
---

<link rel="stylesheet" href="styles.css" type="text/css">

#### Book Review  
##### Mind and Matter: A Life in Math and Football  
##### John Urschel  

February 27, 2020

It's been a few months since I turned the last page on this one, but the themes still resonate. John Urschel is a retired NFL football player pursuing his PhD in Mathematics at MIT. American culture at large believes in a discordance between brains and brawn. Refreshingly, Urschel does not subscribe to prevailing opinion. Whether on the gridiron or in the stacks, Urschel demonstrates grit. He has a lesson to impart about the synergy of athletics and academics. Check this one out if you want to see a vibrant mind and enviable work ethic in action.  




#### Roasting the Poster

October 21, 2019  

"The cardinal sin of every poster I've seen, including the posters I've designed myself, is that they assume people are going to stand there and read our posters in silence for 10 straight minutes, following the order of the sections we've laid out," argues Mike Morrison in a recent [Youtube video](https://www.youtube.com/watch?v=1RwJbhkCA58).

Morrison is an organizational psychology student at Michigan State who believes there is a better way to share knowledge at conferences. His [#betterposter template](https://osf.io/ef53g/) is dominated by a center panel describing the presenter's contribution to science in one supersized sentence. The limited real estate left forces extraneous words and plots to the cutting room floor.

Not everyone agrees with Morrison's streamlined design. The format sparked heated debate at my department's PhD student journal club this week. It became clear that our disagreement stemmed from one contested question: what _is_ the purpose of a poster session, anyway? Is it to connect with the few subject matter experts who will understand a more detailed poster? Or to disseminate your findings to a wide audience?

We'll see how my adoption of the #betterposter template is received at [Public Health Research Day](https://www.brown.edu/academics/public-health/public-health-research-day) in April. Until then, my internal jury remains hung.
